### ISSUE TITLE
Hi, I want to enquire that whether this library can do regression analysis? thanks

### ISSUE THREAD

**Issue by Qiuchumo** [theogf/BayesianSVM.jl#1]

**Comment by theogf** [comment]
Hello,
This package is based on SVM, which goal is to solve classification problems. Therefore, it is not usable for regression. I would recommend to look at GP regression (on which our model is based) for you regression analysis.

**Comment by Qiuchumo** [comment]
Thanks,  this method is so attractive,  do you think it will have the ability to do regression analysis if change something?

**Comment by theogf** [comment]
Hello,
I am working on a new more general package where you will be able to do Regression (based on Hensmann work) with the same features, you can find github.com/theogf/OMGP.jl
Although it is still quite in development
