### ISSUE TITLE
LoadError when call BaysianSVM from python through pyjulia

### ISSUE THREAD

**Issue by zgbkdlm** [theogf/BayesianSVM.jl#2]
Environment:
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux

julia> VERSION
v"0.6.2"
```

All required dependencies are installed.

When try to call BayesianSVM from python:

```
import julia

j = julia.Julia()

j.using("BayesianSVM")
```

Error occurred:

```
LoadError("/home/zzz/.julia/v0.6/BayesianSVM/src/BayesianSVM.jl", 10, InitError(:PyPlot, UndefVarError(:pyprogramname)))Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 467, in using
    self.eval("using %s" % module)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 449, in eval
    ans = self._call(src)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 412, in _call
    self.check_exception(src)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 432, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'LoadError' occurred while calling julia code:
using BayesianSVM
```

**Comment by theogf** [comment]
Hello, and thanks for the feedback you are probably missing the PyPlot package in Julia (Pkg.add("PyPlot")). 
I realised the required packages were missing,  I updated the list, now reinstalling should work or simply adding the missing packages.

**Comment by zgbkdlm** [comment]
Hi,
Thanks for your answer, but it seems that PyPlot may not be the reason, because I've already have it installed. 

```
julia> Pkg.add("PyPlot")
INFO: Package PyPlot is already installed
```

**Comment by theogf** [comment]
I was not able to reproduce your error (although I am using python2.7). One last suggestion I would have would be to be sure to connect correctly PyCall by setting
```julia> ENV["PYTHON"]="path/to/conda/python"
julia>Pkg.build("PyCall")
julia>using PyCall, PyPlot
```
In another note if you are interested I would suggest you to use a more general package I am currently developing which also include the BayesianSVM : https://github.com/theogf/OMGP.jl
Where the UI is mostly the same :
```
model = SparseBSVM(X,y,kernel=RBFKernel(1.0),m=10)
model.train()
y=model.predict(X_test)
```

**Comment by zgbkdlm** [comment]
Hi,

Thanks for your time. Yes, it would be very hard to reproduce such error. 
I think there got be something wrong with the PyPlot. 
Because when I call it in Python
```
>>> j.using("PyPlot")
InitError(:PyPlot, UndefVarError(:pyprogramname))Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 467, in using
    self.eval("using %s" % module)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 449, in eval
    ans = self._call(src)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 412, in _call
    self.check_exception(src)
  File "/home/zzz/anaconda3/lib/python3.6/site-packages/julia/core.py", line 432, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'InitError' occurred while calling julia code:
using PyPlot
```

 I think the actual problem may lie in my python environment. I just tried this in another computer, and it work.

BTW, how do I do the multi-class classification?

Let's close this issue then~

Thanks a lot

**Comment by theogf** [comment]
For multi-class classification, this is a entire other problem, but I am currently working on it, and there should be a release at some point this year (on OMGP.jl).
